### ISSUE TITLE
Please remove while loop

### ISSUE THREAD

**Issue by nwhean** [sirhcofe/fdf#2]
The while loop in this function can be removed with a bit of math. 

https://github.com/sirhcofe/fdf/blob/c327f03313799dbb28a4bd48a14d85fdf8c4b420/fildefer/draw-aa-line/drawaaline_utils.c#L20

This while loop will probably come back to haunt you. Imagine having to run an average of over 500 loops for each pixel...

**Comment by sirhcofe** [comment]
Hi nwhean, taking your advice into consideration, the while loop has been changed into math operations.

https://github.com/sirhcofe/fdf/blob/87c194f5838cdec6d7e6665fb1e4488a33481473/fildefer/draw_line/drawaaline.c#L28
