### ISSUE TITLE
Potential bug for negative input?

### ISSUE THREAD

**Issue by nwhean** [sirhcofe/fdf#3]
I can't be sure since I'm only reading your code, and not running it, but it seems like you are trying to get the fractional value of a number. Seems to me your function will produce error for negative input.  https://github.com/sirhcofe/fdf/blob/c327f03313799dbb28a4bd48a14d85fdf8c4b420/fildefer/draw-aa-line/drawaaline_utils.c#L44

Also, can't you just use the fmod function?

**Comment by sirhcofe** [comment]
Hi nwhean, thanks for the pointing out the issue, please refer to recent changes for rectifications.
